### ISSUE TITLE
Garbage collect old data

### ISSUE THREAD

**Issue by zner0L** [datenanfragen/backend#5]
Comments that have not been accepted for a while should not be kept in the database. I would suggest not more than two weeks until old comments are removed.

I can see two ways to do this:
* a regular cron job
* something like [hapi-cron](https://github.com/antonsamper/hapi-cron)

**Comment by baltpeter** [comment]
Absolutely. I have wanted to implement that for quite a while but never got around to that considering how annoying developing the lambdas was. This should not be an issue anymore.

Without putting too much thought into it, I would vote for hapi-cron. I would like to avoid external dependencies where possible, especially since we are running on an Uberspace.

**Comment by mal-tee** [comment]
* Why aren't we introducing a "reject"-Button instead of not-accepting? 

* What happens if you two are too busy/unavailable for two weeks or simply forget too accept a comment? Then this would delete comments blindly, right?

**Comment by baltpeter** [comment]
>     * Why aren't we introducing a "reject"-Button instead of not-accepting?

We can do that as well.

>     * What happens if you two are too busy/unavailable for two weeks or simply forget too accept a comment? Then this would delete comments blindly, right?

I feel like that is pretty unlikely. :D But if push comes to shove, we will most likely not have deleted the confirmation email either. And that mail contains all the details, so we would be able to recreate the comment from that.

On the other hand, it is much more important to delete comments that we don't accept because some of them contain a _worrying_ amount of personal data that we definitely don't want to keep around. Just relying on a 'reject' button isn't enough imho as that can be easily forgotten.

**Comment by mal-tee** [comment]
Right. The private data. I agree with auto-removing.

**Comment by zner0L** [comment]
I'll also need garbage collection for old `mollie_ids`. I think in AWS we keep them 30 days.
